const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.SVGPicture,
		C3.Behaviors.Physics,
		C3.Behaviors.Fade,
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.Button,
		C3.Plugins.DrawingCanvas,
		C3.Plugins.Text,
		C3.Plugins.Json,
		C3.Plugins.Dictionary,
		C3.Plugins.AJAX,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.SVGPicture.Acts.AddInstanceVar,
		C3.Plugins.SVGPicture.Acts.SetImageByName,
		C3.Plugins.SVGPicture.Acts.SetSize,
		C3.Plugins.System.Exps.min,
		C3.Plugins.SVGPicture.Cnds.CompareInstanceVar,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Plugins.SVGPicture.Acts.SetVisible,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.SVGPicture.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Physics.Acts.SetDensity,
		C3.Plugins.SVGPicture.Acts.RotateClockwise,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.SetVar,
		C3.ScriptsInEvents["Event-Blatt1_Event11_Act1"],
		C3.Plugins.DrawingCanvas.Acts.ClearCanvas,
		C3.Plugins.System.Exps.rgba,
		C3.Plugins.DrawingCanvas.Acts.Line,
		C3.Plugins.SVGPicture.Exps.X,
		C3.Plugins.SVGPicture.Exps.Y,
		C3.Plugins.SVGPicture.Cnds.IsOnScreen,
		C3.Plugins.Json.Cnds.HasKey,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.DrawingCanvas.Acts.SetVisible,
		C3.Plugins.System.Cnds.PickRandom
	];
};
self.C3_JsPropNameTable = [
	{age: 0},
	{QuestName: 0},
	{anzahl: 0},
	{schuessAngle: 0},
	{user: 0},
	{changeSetID: 0},
	{Physik: 0},
	{Verblassen: 0},
	{Quest: 0},
	{Sprite: 0},
	{Maus: 0},
	{Button: 0},
	{SCBanner: 0},
	{LeinwandZeichnen: 0},
	{Text: 0},
	{JSON: 0},
	{QuestQuestions: 0},
	{AJAX: 0},
	{chosenChangeSetID: 0}
];

self.InstanceType = {
	Quest: class extends self.ISVGPictureInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Maus: class extends self.IInstance {},
	Button: class extends self.IButtonInstance {},
	SCBanner: class extends self.ISVGPictureInstance {},
	LeinwandZeichnen: class extends self.IDrawingCanvasInstance {},
	Text: class extends self.ITextInstance {},
	JSON: class extends self.IJSONInstance {},
	QuestQuestions: class extends self.IDictionaryInstance {},
	AJAX: class extends self.IInstance {}
}